from app.core.config import settings

# Core Kafka Topics
TOPIC_RECENT_CHANGE = settings.TOPIC_RECENT_CHANGE
TOPIC_ARTICLE_PROCESSED = settings.TOPIC_ARTICLE_PROCESSED
TOPIC_TREND_DETECTED = settings.TOPIC_TREND_DETECTED
TOPIC_EMBEDDING_CREATED = settings.TOPIC_EMBEDDING_CREATED
TOPIC_ANALYSIS_COMPLETED = settings.TOPIC_ANALYSIS_COMPLETED
TOPIC_DLQ = settings.TOPIC_DLQ

ALL_TOPICS = [
    TOPIC_RECENT_CHANGE,
    TOPIC_ARTICLE_PROCESSED,
    TOPIC_TREND_DETECTED,
    TOPIC_EMBEDDING_CREATED,
    TOPIC_ANALYSIS_COMPLETED,
    TOPIC_DLQ,
]
