from typing import Any, Dict, List, Optional, TYPE_CHECKING
from sqlalchemy import Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.trend import TrendEvent


class AIAnalysis(Base, TimestampMixin):
    """
    Persisted evidence-backed AI analysis generated by the LLM Gateway.
    """
    __tablename__ = "ai_analyses"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    trend_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("trend_events.id", ondelete="CASCADE"), nullable=True, index=True)
    article_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    importance: Mapped[str] = mapped_column(String(32), default="medium", nullable=False)
    detected_topic: Mapped[str] = mapped_column(String(128), default="General", nullable=False)
    change_type: Mapped[str] = mapped_column(String(64), default="factual_update", nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=0.8, nullable=False)
    evidence_points: Mapped[List[str]] = mapped_column(JSON, default=list, nullable=False)
    citations_json: Mapped[List[Dict[str, Any]]] = mapped_column(JSON, default=list, nullable=False)
    
    # Provider metadata & traceability
    provider: Mapped[str] = mapped_column(String(64), nullable=False)
    model: Mapped[str] = mapped_column(String(64), nullable=False)
    was_fallback: Mapped[bool] = mapped_column(default=False, nullable=False)
    latency_ms: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Relationships
    trend: Mapped[Optional["TrendEvent"]] = relationship("TrendEvent", back_populates="analyses")
